package lv.bootcamp.shelter.repository;

import lv.bootcamp.shelter.model.Animal;
import lv.bootcamp.shelter.model.AnimalStatus;
import lv.bootcamp.shelter.model.AnimalType;
import org.springframework.stereotype.Repository;

import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;

// Generated by GitHub Copilot
/**
 * In-memory data store for shelter animals.
 * Acts as the data access layer — AnimalService delegates to this class.
 * No database is used; all data resets on each application restart.
 * Pre-seeded with five animals on startup.
 */
@Repository
public class AnimalRepository {

    private final Map<Long, Animal> store = new ConcurrentHashMap<>();
    private final AtomicLong idSequence = new AtomicLong();

    public AnimalRepository() {
        seed("Luna",   AnimalType.CAT,   "British Shorthair", 2,
                "Calm and affectionate. Loves cuddles.",
                "https://placehold.co/300x200/FFD700/000?text=Luna",
                AnimalStatus.AVAILABLE);
        seed("Max",    AnimalType.DOG,   "Labrador",          4,
                "Energetic and friendly. Great with kids.",
                "https://placehold.co/300x200/4169E1/fff?text=Max",
                AnimalStatus.AVAILABLE);
        seed("Bella",  AnimalType.DOG,   "Poodle",            1,
                "Playful and intelligent. Already trained.",
                "https://placehold.co/300x200/4169E1/fff?text=Bella",
                AnimalStatus.ADOPTED);
        seed("Oliver", AnimalType.CAT,   "Orange Tabby",      3,
                "Independent but friendly. Indoor only.",
                "https://placehold.co/300x200/FFD700/000?text=Oliver",
                AnimalStatus.AVAILABLE);
        seed("Pepper", AnimalType.OTHER, "Rabbit",            2,
                "Gentle and curious. Loves fresh vegetables.",
                "https://placehold.co/300x200/32CD32/000?text=Pepper",
                AnimalStatus.AVAILABLE);
    }

    /**
     * Returns an atomically incremented ID for use when creating a new animal.
     */
    public long nextId() {
        return idSequence.incrementAndGet();
    }

    /**
     * Returns all animals sorted by ID.
     */
    public List<Animal> findAll() {
        return store.values().stream()
                .sorted(Comparator.comparingLong(Animal::getId))
                .toList();
    }

    /**
     * Returns a single animal by ID, or empty if not found.
     */
    public Optional<Animal> findById(Long id) {
        return Optional.ofNullable(store.get(id));
    }

    /**
     * Persists an animal. The animal must already have an ID assigned via nextId().
     */
    public Animal save(Animal animal) {
        store.put(animal.getId(), animal);
        return animal;
    }

    private void seed(String name, AnimalType type, String breed, int age,
                      String description, String imageUrl, AnimalStatus status) {
        long id = idSequence.incrementAndGet();
        store.put(id, new Animal(id, name, type, breed, age, description, status, imageUrl));
    }
}
