package lv.bootcamp.shelter.service;

import lombok.RequiredArgsConstructor;
import lv.bootcamp.shelter.dto.AnimalCreateRequest;
import lv.bootcamp.shelter.dto.AnimalResponse;
import lv.bootcamp.shelter.form.AnimalForm;
import lv.bootcamp.shelter.model.Animal;
import lv.bootcamp.shelter.model.AnimalStatus;
import lv.bootcamp.shelter.repository.AnimalRepository;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

// Generated by GitHub Copilot
/**
 * Business logic for shelter animal management.
 * Delegates data storage to AnimalRepository.
 * Lombok generates the constructor for AnimalRepository injection.
 */
@Service
@RequiredArgsConstructor
public class AnimalService {

    private final AnimalRepository animalRepository;

    /**
     * Returns all animals sorted by ID.
     */
    public List<AnimalResponse> findAll() {
        return animalRepository.findAll().stream()
                .map(this::toResponse)
                .toList();
    }

    /**
     * Returns a single animal by ID, or empty if not found.
     */
    public Optional<AnimalResponse> findById(Long id) {
        return animalRepository.findById(id).map(this::toResponse);
    }

    /**
     * Creates a new animal with status AVAILABLE and persists it.
     */
        public AnimalResponse create(AnimalCreateRequest request) {
        return createAnimal(
            request.name(),
            request.type(),
            request.breed(),
            request.age(),
            request.description(),
            request.imageUrl()
        );
        }

        /**
         * Creates a new animal from the server-rendered page form.
         */
        public AnimalResponse createFromForm(AnimalForm form) {
        return createAnimal(
            form.name(),
            form.type(),
            form.breed(),
            form.age(),
            form.description(),
            form.imageUrl()
        );
        }

        private AnimalResponse createAnimal(
            String name,
            lv.bootcamp.shelter.model.AnimalType type,
            String breed,
            Integer age,
            String description,
            String imageUrl
        ) {
        long id = animalRepository.nextId();
        Animal animal = new Animal(
                id,
            name,
            type,
            breed,
            age,
            description,
                AnimalStatus.AVAILABLE,
            imageUrl
        );
        return toResponse(animalRepository.save(animal));
    }

    private AnimalResponse toResponse(Animal animal) {
        return new AnimalResponse(
                animal.getId(),
                animal.getName(),
                animal.getType(),
                animal.getBreed(),
                animal.getAge(),
                animal.getDescription(),
                animal.getStatus(),
                animal.getImageUrl()
        );
    }
}
