package lv.bootcamp.shelter;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

// Generated by GitHub Copilot
@SpringBootTest
class ShelterApplicationTests {

    @Test
    void contextLoads() {
    }
}
